image: "rust:1.39"

variables:
  CARGO_HOME: /root/.cargo

before_script:
  - rustup component add rustfmt
  - rustc --version
  - rustfmt --version

precommit:
  script:
    - curl https://pre-commit.com/install-local.py | python -
    - $HOME/bin/pre-commit run --all-files

cargo:
  script:
    - cargo test
  cache:
    key:
      files:
        - Cargo.lock
    paths:
      - /root/.cargo/registry
      - target/
